HR:
  commands:
  - echo Deploying HR software version 2.3.4
  environment: production
  version: 2.3.4
finance:
  commands:
  - echo Deploying finance software version 1.2.3
  environment: staging
  version: 1.2.3
